### ISSUE TITLE
Many errors using with LibreElec Matrix version

### ISSUE THREAD

**Issue by hoksilato2** [mikesilvo164/script.skinshortcuts#17]
Hardware: Raspberry Pi 4
SO: LibreElec Milhouse #414. Updated from 9.2 stable (with Kodi v18)
Kodi version: v19 (Matrix)
Skin: skin.aura

All the time kodi shows me a skinshortcuts add-on error. The settings for widgets on "Customization home menu" not working, but widgets in the main menu works ok. I can't edit widgets settings.

I know that all this works are in alpha versions but, maybe these logs will help to improve this fantastic tool :)

Thanks for effort and gratz for your work!

**Comment by hoksilato2** [comment]
The log:

> 2020-04-15 18:45:36.548 T:2496 WARNING: Trying to add unsupported control type 1
> 2020-04-15 18:45:37.505 T:11480   ERROR: Traceback (most recent call last):
> 2020-04-15 18:45:37.505 T:11480   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/datafunctions.py", line 550, in _get_additionalproperties
>                                                 listProperties = ast.literal_eval( file )
> 2020-04-15 18:45:37.505 T:11480   ERROR:   File "/usr/lib/python3.7/ast.py", line 46, in literal_eval
> 2020-04-15 18:45:37.505 T:11480   ERROR:   File "/usr/lib/python3.7/ast.py", line 35, in parse
> 2020-04-15 18:45:37.505 T:11480   ERROR:   File "<unknown>", line 209
> 2020-04-15 18:45:37.505 T:11480   ERROR:     ['mainmenu', '33060', 'icon', 'special://skin/extras/icons/pow
> 2020-04-15 18:45:37.505 T:11480   ERROR:                                                                  ^
> 2020-04-15 18:45:37.505 T:11480   ERROR: SyntaxError: EOL while scanning string literal
> 2020-04-15 18:45:37.521 T:11480   ERROR: Traceback (most recent call last):
> 2020-04-15 18:45:37.521 T:11480   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 88, in buildMenu
>                                                 self.writexml( profilelist, mainmenuID, groups, numLevels, buildMode, progress, options, minitems )
> 2020-04-15 18:45:37.522 T:11480   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 532, in writexml
>                                                 if buildMode == "single" and not len( submenuitems ) == 0 and not isinstance( item, basestring ):
> 2020-04-15 18:45:37.522 T:11480   ERROR: NameError: name 'basestring' is not defined
> 2020-04-15 18:45:37.548 T:11480   ERROR: GetDirectory - Error getting /storage/.kodi/media/Fonts/
> 2020-04-15 18:45:37.548 T:11480   ERROR: GetDirectory - Error getting special://home/media/Fonts/
> 2020-04-15 18:45:37.601 T:11480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'TypeError'>
>                                             Error Contents: function takes at most 2 arguments (3 given)
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/script.skinshortcuts/default.py", line 3, in <module>
>                                                 skinshortcuts.Main()
>                                               File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/skinshortcuts.py", line 58, in __init__
>                                                 XML.buildMenu( self.MENUID, self.GROUP, self.LEVELS, self.MODE, self.OPTIONS, self.MINITEMS )
>                                               File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 150, in buildMenu
>                                                 xbmcgui.Dialog().ok( ADDON.getAddonInfo( "name" ), LANGUAGE( 32092 ), LANGUAGE( 32094 ) )
>                                             TypeError: function takes at most 2 arguments (3 given)
>                                             -->End of Python script error report<--
> 2020-04-15 18:45:38.050 T:2496 WARNING: Trying to add unsupported control type 1
> 2020-04-15 18:45:39.772 T:11503   ERROR: Traceback (most recent call last):
> 2020-04-15 18:45:39.772 T:11503   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/datafunctions.py", line 550, in _get_additionalproperties
>                                                 listProperties = ast.literal_eval( file )
> 2020-04-15 18:45:39.772 T:11503   ERROR:   File "/usr/lib/python3.7/ast.py", line 46, in literal_eval
> 2020-04-15 18:45:39.772 T:11503   ERROR:   File "/usr/lib/python3.7/ast.py", line 35, in parse
> 2020-04-15 18:45:39.772 T:11503   ERROR:   File "<unknown>", line 209
> 2020-04-15 18:45:39.772 T:11503   ERROR:     ['mainmenu', '33060', 'icon', 'special://skin/extras/icons/pow
> 2020-04-15 18:45:39.772 T:11503   ERROR:                                                                  ^
> 2020-04-15 18:45:39.772 T:11503   ERROR: SyntaxError: EOL while scanning string literal
> 2020-04-15 18:45:39.904 T:11503   ERROR: EXCEPTION: Non-Existent Control 111
> 2020-04-15 18:45:39.905 T:11503   ERROR: EXCEPTION: Non-Existent Control 309
> 2020-04-15 18:45:39.905 T:11503   ERROR: EXCEPTION: Unknown control type for python
> 2020-04-15 18:45:39.973 T:11508   ERROR: GetDirectory - Error getting /storage/.kodi/userdata/library/music
> 2020-04-15 18:46:29.168 T:11574   ERROR: Traceback (most recent call last):
> 2020-04-15 18:46:29.168 T:11574   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/datafunctions.py", line 550, in _get_additionalproperties
>                                                 listProperties = ast.literal_eval( file )
> 2020-04-15 18:46:29.168 T:11574   ERROR:   File "/usr/lib/python3.7/ast.py", line 46, in literal_eval
> 2020-04-15 18:46:29.168 T:11574   ERROR:   File "/usr/lib/python3.7/ast.py", line 35, in parse
> 2020-04-15 18:46:29.168 T:11574   ERROR:   File "<unknown>", line 209
> 2020-04-15 18:46:29.168 T:11574   ERROR:     ['mainmenu', '33060', 'icon', 'special://skin/extras/icons/pow
> 2020-04-15 18:46:29.168 T:11574   ERROR:                                                                  ^
> 2020-04-15 18:46:29.169 T:11574   ERROR: SyntaxError: EOL while scanning string literal
> 2020-04-15 18:46:29.221 T:11574   ERROR: EXCEPTION: Non-Existent Control 111
> 2020-04-15 18:46:29.222 T:11574   ERROR: EXCEPTION: Non-Existent Control 309
> 2020-04-15 18:46:29.222 T:11574   ERROR: EXCEPTION: Unknown control type for python
> 2020-04-15 18:46:29.276 T:11579   ERROR: GetDirectory - Error getting /storage/.kodi/userdata/library/music
>

**Comment by mikesilvo164** [comment]
Post a complete debug log please

**Comment by hoksilato2** [comment]
I attach you the log after restart.

[kodi.log](https://github.com/mikesilvo164/script.skinshortcuts/files/4482713/kodi.log)

**Comment by mikesilvo164** [comment]
Please correctly install the latest version from master branch and test.

**Comment by mikesilvo164** [comment]
This is skin instructions but if followed work for all add-ons
https://forum.kodi.tv/showthread.php?tid=210069&pid=1850231#pid1850231

**Comment by mikesilvo164** [comment]
Idk if thumbs up means it's all working now but I assume that it is so I'll close this issue.

**Comment by hoksilato2** [comment]
Hi @mikesilvo164,

Thank you so much, the initial errors are gone but, when I try to config the menus, old config is deleted. I can config widgets again, but the submenus doesn't work.

If I restore files of _.\addon_data\script.skinshortcuts_ with my backup, all works again but I can't edit with Kodi's GUI.

When I try to edit some menu log show this:

```
2020-04-16 16:44:13.352 T:2499  NOTICE:   load skin from: /storage/.kodi/addons/skin.aura/ (version: 1.0.5)
2020-04-16 16:44:14.017 T:2499   ERROR: Window Translator: Can't find window infodialog
2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3002
2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3003
2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3004
2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3005
2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3006
2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3007
2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3008
2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3009

```

I trying to config menus with xml files, but I don't know if is a good idea 😆

**Comment by hoksilato2** [comment]
> Idk if thumbs up means it's all working now but I assume that it is so I'll close this issue.

Oh wow, I was redacting the last message. Sorry!

**Comment by mikesilvo164** [comment]
> Hi @mikesilvo164,
> 
> Thank you so much, the initial errors are gone but, when I try to config the menus, old config is deleted. I can config widgets again, but the submenus doesn't work.
> 
> If I restore files of _.\addon_data\script.skinshortcuts_ with my backup, all works again but I can't edit with Kodi's GUI.
> 
> When I try to edit some menu log show this:
> 
> ```
> 2020-04-16 16:44:13.352 T:2499  NOTICE:   load skin from: /storage/.kodi/addons/skin.aura/ (version: 1.0.5)
> 2020-04-16 16:44:14.017 T:2499   ERROR: Window Translator: Can't find window infodialog
> 2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3002
> 2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3003
> 2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3004
> 2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3005
> 2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3006
> 2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3007
> 2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3008
> 2020-04-16 16:44:14.111 T:2499 WARNING: Skin has invalid include: skinshortcuts-template-widget3009
> ```
> 
> I trying to config menus with xml files, but I don't know if is a good idea 😆

None of that is script related.
