### ISSUE TITLE
Playlist - incorrect action

### ISSUE THREAD

**Issue by BobCratchett** [mikesilvo164/script.skinshortcuts#2]
When choosing action for menu, then selecting a playlist, then choosing to 'Display' it, the action is wrong: `::PLAYLIST>video::`

The actions with ::'s around them are used internally by the script, so at some point in library.py, this isn't getting translated by the script into an actually valid action.

**Comment by mikesilvo164** [comment]
I think I have this one fixed with https://github.com/mikesilvo164/script.skinshortcuts/commit/c7c6320e22141c8a6b0d3f5335fbc4d7f8e856ce

**Comment by mikesilvo164** [comment]
@BobCratchett Is this still an issue?

**Comment by BobCratchett** [comment]
This is now working correctly :)
