### ISSUE TITLE
[Meta] Status of the Add-on

### ISSUE THREAD

**Issue by finkleandeinhorn** [mikesilvo164/script.skinshortcuts#20]
I'm currently a maintainer of @marcelveldt's repository, under @kodi-community-addons, where I understand many previous versions of this add-on have been served from in the past.

As this fork appears to be the most up-to-date, I'm simply trying to reach out and find the status of this project. I understand that it is being (or has been?) converted to Python 3, in preparation for Kodi Matrix and beyond... but is this the "official" version now? Are there plans for ongoing support for Kodi Leia and below? If not, which version would *you* recommend using?

Is this version on a repo for easy installation? Will it be merged to Kodi's official repository? If this is to be the successive version to whatever is in the official repo and in `repository.marcelveldt`, has there been thought given to the previous two questions?

Is this repo the best place for other developers to submit PRs or issues?

**Comment by drinfernoo** [comment]
I'm also curious about this. I'd like to pontentially propose changes to better support an add-on I'm working on, and am wondering about the best way to go about having those fixes bring widely available.

**Comment by finkleandeinhorn** [comment]
@drinfernoo Agreed, that's part of why I raised this issue. It seems there are a number of forks floating around in different repos, with varying degrees of development, but it's hard to pin down which changes are worthwhile, and which fork should be considered "official".

**Comment by Ch1llb0** [comment]
Checkout the Kodi forum thread for this addon: @mikesilvo164 is also active there. I've been told, this is the fork to go with. Probably good to also ping him there.

**Comment by finkleandeinhorn** [comment]
Could any of the maintainers respond?

**Comment by drinfernoo** [comment]
Possibly @mikesilvo164 or @BobCratchett may have more input? It seems that development hasn't stopped, but not much is being said about this.

Considering the [recent change to ABI for xbmcgui](https://github.com/xbmc/xbmc/pull/18082) (meaning Leia skins won't install in Matrix)... it's about to be very important that a Matrix-compatible version of this add-on is widely available, and accessible to "normal" users.

**Comment by mikesilvo164** [comment]
A Matrix compatible version is already on the Kodi repo

**Comment by drinfernoo** [comment]
Ah, so there is! Is this the proper place for bringing up issues and/or contributing, then?

**Comment by mikesilvo164** [comment]
Sure. I've been very busy with RL stuff lately but I do what I can when I can 😃
