### ISSUE TITLE
Add enable addon functionality

### ISSUE THREAD

**Issue by Ch1llb0** [mikesilvo164/script.skinshortcuts#23]
With v19 there's a new built-in function for Kodi that allows skinners to add a direct button for [enabling an addon](https://kodi.wiki/view/List_of_built-in_functions#Add-on_built-in.27s). The skinshortcuts script can install an addon via the `::INSTALL::` tag, but it cannot enable an addon AFAICT. Would it be possible to add an `::ENABLE::` tag of some sorts in order to be able to let users enable a disabled addon like the skin helper script or some other script that can be used together with the skinshortcuts script?

**Comment by Ch1llb0** [comment]
Added with https://github.com/mikesilvo164/script.skinshortcuts/pull/35

**Comment by anxdpanic** [comment]
Added in https://github.com/mikesilvo164/script.skinshortcuts/releases/tag/2.0.0.alpha2 or higher
