### ISSUE TITLE
New Itens

### ISSUE THREAD

**Issue by joaosagrath** [mikesilvo164/script.skinshortcuts#27]
Since Retroplayer was introduce in kodi, we have two more Itens:

Games Addons
Games Folders (basically the same as image sources)

Can you please add these two itens?

Cheers

**Comment by Ch1llb0** [comment]
When providing a custom dialog to adjust the home menu with your skin, you may add those manually. For an example, see here: https://github.com/Ch1llb0/skin.osmc/blob/matrix/shortcuts/overrides.xml

**Comment by joaosagrath** [comment]
Closing this issue!
