### ISSUE TITLE
$PYTHON evaluations using 'in' is reversed, breaks a few skins (template.xml)

### ISSUE THREAD

**Issue by inb4after** [mikesilvo164/script.skinshortcuts#29]
The documentation states:

> Whilst 'in' is available, for technical reasons its operation is reversed, so if you want to know if `x` is in `y`, you'd use `if y in x`.

However, after the py3 conversion, this is doubly reversed back to `if x in y`.

This does break some skins like Aura and AuraMOD, the latter of which we used a workaround to prevent this issue, see [this commit](https://github.com/SerpentDrago/skin.auramod/commit/a86d78cd50d35b2448632188edaee159fc8fe67f) of skin.auramod (Kodi 19 migration status: WIP)

For example in [Line 91](https://github.com/SerpentDrago/skin.auramod/commit/a86d78cd50d35b2448632188edaee159fc8fe67f#diff-dee7d6035ac5d69bac962c84bfd887b6fb77cb9f6588ebac154be131237172deL91) the existing code was:

`$PYTHON['true' if widgetPath in 'plugin:' else 'false']`

and the two methods to make this line work again are:

1 - `$PYTHON['true' if 'plugin:' in widgetPath else 'false']`

2 - `$PYTHON['true' if widgetPath == 'plugin:' else 'false']`

We used method 2 for future-proofing if this addon (script.skinshortcuts) is fixed and makes the python a little easier to read.

If this issue is fixed, it would prevent the need for other skins' shortcuts to be fixed, for example the original [skin.aura](https://github.com/jurialmunkey/skin.aura) by jurialmunkey and the respective [Aura Kodi 19 port](https://github.com/kcook98765/skin.aura) currently underway by kcook98765

**Comment by anxdpanic** [comment]
Looks like this was previously resolved, please re-open if the issue persists
