### ISSUE TITLE
Include rebuild not triggered after template changes

### ISSUE THREAD

**Issue by Ch1llb0** [mikesilvo164/script.skinshortcuts#33]
I've come across a very strange issue mentioned here on the forum already: https://forum.kodi.tv/showthread.php?tid=178294&pid=3026461#pid3026461

When the template.xml file has been changed, the script used to rebuild the home menu include.xml when first firing up Kodi after the changes under v18 (with Python v2 code). Now, with v19 and Python v3, it doesn't anymore. The rebuild is only triggered, if you go to the customization dialog, change an item and return to whatever window features the script rebuild line in an onload... I'm using this rebuild line that used to work just fine:

`<onload condition="System.HasAddon(script.skinshortcuts)">RunScript(script.skinshortcuts,type=buildxml&amp;mainmenuID=9000&amp;group=mainmenu&amp;levels=1&amp;options=noGroups)</onload>`

Is there something wrong with the script which prevents an automatic rebuild once the template.xml code has been changed?

**It's vital that this works** as it leads to empty home menus for users of my skin as I reworked the way colours are selected and shown via variables. The template.xml uses those new variables, but the script doesn't rebuild the home menu include file automatically to reflect that change - it leads to this: https://discourse.osmc.tv/t/testing-kodi-v19-builds-for-vero-4k-4k/89151/499?u=chillbo

**Comment by Ch1llb0** [comment]
Just to add to this... If the template.xml file has been changed, logs show that the script still returns `2021-08-16 16:39:08.823 T:10536   DEBUG <general>: script.skinshortcuts: Menu is up to date` although it shouldn't. The underlying check seems to return the wrong value for instances where the menu should be rebuilt.

**Comment by Ch1llb0** [comment]
Is this related and a long-standing bug that hasn't been fixed yet? https://github.com/mikesilvo164/script.skinshortcuts/issues/3#issuecomment-529139935

**Comment by Ch1llb0** [comment]
Solved in https://github.com/mikesilvo164/script.skinshortcuts/pull/35

**Comment by anxdpanic** [comment]
Re-open if issue persists with https://github.com/mikesilvo164/script.skinshortcuts/releases/tag/2.0.0.alpha2 or higher
