### ISSUE TITLE
Weblate and Add-on Submission

### ISSUE THREAD

**Issue by anxdpanic** [mikesilvo164/script.skinshortcuts#39]
@mikesilvo164 

When you have a chance, I need a few things added from your side on GitHub.

To add this script to Weblate for translations I need a webhook added to this repository.
- https://github.com/mikesilvo164/script.skinshortcuts/settings/hooks/
  - Payload URL: `https://kodi.weblate.cloud/hooks/github`
  - Which events would you like to trigger this webhook?: `Just the push event.`

For automated add-on submission to Kodi's Official Repository I need a token/secret added to this repository.

1. Create a Personal Access Token with `repo` scope, and save it somewhere private for future use.
https://github.com/settings/tokens 

2. Add that token to this repositories secrets with the name `ADDON_SUBMISSION_TOKEN` https://github.com/mikesilvo164/script.skinshortcuts/settings/secrets/actions

If you have any questions, don't hesitate.
Cheers!

**Comment by mikesilvo164** [comment]
@anxdpanic Should be good to go, please let me know if I made a mistake 🙂

**Comment by anxdpanic** [comment]
Huge thank you! 😄 
I won't be able to test the add-on submission part until it comes time, I don't expect any issues though.
I should have Weblate done today though 😄 

If you want help with either of these in your other repositories in the future, just give me a ping!

**Comment by anxdpanic** [comment]
@mikesilvo164 
Can you have a look at the second part of this issue, authentication is failing for the submission, might be the token.

https://github.com/mikesilvo164/script.skinshortcuts/runs/4915105673?check_suite_focus=true#step:7:25

> For automated add-on submission to Kodi's Official Repository I need a token/secret added to this repository.
>
> 1. Create a Personal Access Token with `repo` scope, and save it somewhere private for future use.
> https://github.com/settings/tokens 
>
> 2. Add that token to this repositories secrets with the name `ADDON_SUBMISSION_TOKEN` https://github.com/mikesilvo164/script.skinshortcuts/settings/secrets/actions

I will submit it manually this time, but good to have doubled checked for next time 😃 
Thanks!
