### ISSUE TITLE
Partically broken in kodi 19.3

### ISSUE THREAD

**Issue by eXoterr** [mikesilvo164/script.skinshortcuts#72]
When i'm trying to use this addon with "Pellucid" skin i'm getting error mentioned [here](https://github.com/mikesilvo164/script.skinshortcuts/issues/68). This issue can be fixed by commenting (or removing) this line `self.getControl(7).setLabel(xbmc.getLocalizedString(222))` in "common_utils.py". I didnt look through your addon structure, so this action may cause another bugs. 

P.S. Sorry for my English

Best wishes, eXoterr.

**Comment by anxdpanic** [comment]
Should be resolved in #77, thanks for the heads up

**Comment by anxdpanic** [comment]
closing this as a duplicate to #68
