### ISSUE TITLE
v2.0.0 and v2.0.1 break Kodi on Apple TV

### ISSUE THREAD

**Issue by eengert** [mikesilvo164/script.skinshortcuts#86]
I have Kodi Matrix 19 on Apple TV 4K running Arctic Horizon or Arctic Zephyr Reloaded skins.  Skin Shortcuts v1.1.5 works fine.  When the Skin Shortcuts gets updated to v2.0.0 or v2.0.1, it causes an error and the skin will no longer refresh with customization changes.  And if I change between the skins or update either skin to newer versions of the skins, Kodi then becomes completely unusable - it just loads with a blank home screen and I'm unable to do anything.  My only recourse then is to restore from a backup using Xcode on a Mac connected to the Apple TV.

**Comment by Blurayx** [comment]
please fix this bug.

Thank you

**Comment by Mkkonecny** [comment]
Any updates or is it dead right here?

**Comment by anxdpanic** [comment]
I need a log at the very least.

**Comment by Mkkonecny** [comment]
If somebody can guide me how to get a log from Apple TV, I will do.

**Comment by Ade-AV** [comment]
This is the error I get when switching skins from Arctic Horizon 2 to Estuary, updating Skin Shortcuts to v2.0.1 and then switching back

https://paste.kodi.tv/ecomesucoq

```
2023-02-11 08:28:16.232 T:288808   debug <general>: Python interpreter stopped
2023-02-11 08:28:16.232 T:288808   debug <general>: Thread LanguageInvoker 0x16c253000 terminating
2023-02-11 08:28:17.310 T:288810   debug <general>: found key /userdata/addon_data/script.skinshortcuts/settings.xml
2023-02-11 08:28:17.427 T:288810   debug <general>: found key /userdata/profiles.xml
2023-02-11 08:28:17.429 T:288810   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Application/8ED488F8-2D7D-4423-AEA7-325F2A064E56/Library/Caches/Kodi/userdata/profiles.xml'
                                                   Traceback (most recent call last):
                                                     File "/private/var/mobile/Containers/Data/Application/8ED488F8-2D7D-4423-AEA7-325F2A064E56/Library/Caches/Kodi/addons/script.skinshortcuts/resources/lib/entry_point.py", line 16, in <module>
                                                       script.route()
                                                     File "/private/var/mobile/Containers/Data/Application/8ED488F8-2D7D-4423-AEA7-325F2A064E56/Library/Caches/Kodi/addons/script.skinshortcuts/resources/lib/skinshorcuts/skinshortcuts.py", line 78, in route
                                                       route_method()
                                                     File "/private/var/mobile/Containers/Data/Application/8ED488F8-2D7D-4423-AEA7-325F2A064E56/Library/Caches/Kodi/addons/script.skinshortcuts/resources/lib/skinshorcuts/skinshortcuts.py", line 83, in route_buildxml
                                                       self.xml_func.build_menu(self.MENUID, self.GROUP, self.LEVELS,
                                                     File "/private/var/mobile/Containers/Data/Application/8ED488F8-2D7D-4423-AEA7-325F2A064E56/Library/Caches/Kodi/addons/script.skinshortcuts/resources/lib/skinshorcuts/xmlfunctions.py", line 69, in build_menu
                                                       contents = read_file(profiles_xml)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/private/var/mobile/Containers/Data/Application/8ED488F8-2D7D-4423-AEA7-325F2A064E56/Library/Caches/Kodi/addons/script.skinshortcuts/resources/lib/skinshorcuts/common.py", line 28, in read_file
                                                       with open(filename, mode, encoding=encoding) as file_handle:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Application/8ED488F8-2D7D-4423-AEA7-325F2A064E56/Library/Caches/Kodi/userdata/profiles.xml'
                                                   -->End of Python script error report<--
```

**Comment by Blurayx** [comment]
Thanks for posting your log file. Hopefully milksilvo164 can now fix it😀

**Comment by anxdpanic** [comment]
thanks for the log snippet, ill post a new version 2.0.2 to see if that resolves the issue for you

**Comment by anxdpanic** [comment]
https://github.com/mikesilvo164/script.skinshortcuts/releases/latest

**Comment by Ade-AV** [comment]
Installed 2.0.2 and now getting 'Unable to build menu.'

https://paste.kodi.tv/ujubagikek

Thanks

**Comment by anxdpanic** [comment]
@Ade-AV thanks for the quick turn over and log, 
https://github.com/mikesilvo164/script.skinshortcuts/releases/download/2.0.3.alpha1/script.skinshortcuts-2.0.3.alpha1.zip
Please let me know if that resolves the issue for you.

**Comment by Ade-AV** [comment]
Unresolved with 2.03.alpha1

https://paste.kodi.tv/uyubinomog

**Comment by anxdpanic** [comment]
@Ade-AV 

The issue is moving, this time I'm not sure what's causing it without some more information.

Can you check if `/private/var/mobile/Containers/Data/Application/8ED488F8-2D7D-4423-AEA7-325F2A064E56/Library/Caches/Kodi/userdata/profiles.xml` exists on your device? 

Also can you enable debug logging and reproduce a new log with your current issue. https://kodi.wiki/view/Settings/System/Logging#Debug

**Comment by Ade-AV** [comment]
I don't know how to check this on Apple TV, any ideas?

Can you check if /private/var/mobile/Containers/Data/Application/8ED488F8-2D7D-4423-AEA7-325F2A064E56/Library/Caches/Kodi/userdata/profiles.xml exists on your device?

**Comment by anxdpanic** [comment]
Not sure, never used an Apple TV before.

Can you try with https://github.com/mikesilvo164/script.skinshortcuts/releases/tag/2.0.3.alpha2 and post the debug log, might hint better at what's happening. 

@Blurayx Can you try this version of the add-on too if possible, just to rule out a skin/config issue.

**Comment by eengert** [comment]
> 

I think you can just use the File Manager in Kodi to browse your user profile directory.  Another way that would take more time is to use Xcode to download the container, then browse the container on your computer.  But it can take several hours to download a full Kodi app container, depending on what you have installed in Kodi.

**Comment by Blurayx** [comment]
> Not sure, never used an Apple TV before.
> 
> Can you try with https://github.com/mikesilvo164/script.skinshortcuts/releases/tag/2.0.3.alpha2 and post the debug log, might hint better at what's happening.
> 
> @Blurayx Can you try this version of the add-on too if possible, just to rule out a skin/config issue.

Working 😀

Thank You

**Comment by anxdpanic** [comment]
@Blurayx  Thanks for confirming!

@eengert Can you test the latest alpha as well if you have a chance and let us know. I thought that may have resolved the main thread issue. 

@Ade-AV Looks like this might be skin/config/leftover files causing your issue. I only recently started doing maintenance on this add-on so narrowing that down might be difficult. I would try a different skin that uses this as a way to narrow it down.

**Comment by eengert** [comment]
> @eengert Can you test the latest alpha as well if you have a chance and let us know. I thought that may have resolved the main thread issue.
> 

The latest alpha appears to have resolved the issue.  Thanks.

**Comment by anxdpanic** [comment]
Thanks for confirming, I submitted this version to the official repository.

@Ade-AV If you're still having issues, please open a new issue with the debug log.

**Comment by Ade-AV** [comment]
Seems to be working for me too, thanks
