### ISSUE TITLE
BUG: v2.0.1 contains typo in parameter name for ShowDialog

### ISSUE THREAD

**Issue by DalBrar** [mikesilvo164/script.skinshortcuts#91]
https://github.com/mikesilvo164/script.skinshortcuts/blob/11d26b9014789fb7909e352853e77ec97e2b8a0f/resources/lib/skinshorcuts/library.py#L2477-L2478  

https://github.com/mikesilvo164/script.skinshortcuts/blob/11d26b9014789fb7909e352853e77ec97e2b8a0f/resources/lib/skinshorcuts/common_utils.py#L29  

Line `2478` contains a typo regarding the window title paramter being passed in. It should be `window_title` but is missing the underscore resulting in no title for those effected windows.

**Comment by anxdpanic** [comment]
thanks resolved in latest
https://github.com/mikesilvo164/script.skinshortcuts/releases/latest
